import { PROTECTED_USER_TABS } from '../routing/appRoutes.js';

/**
 * App.jsx의 대형 상태 객체를 화면별 최소 컨텍스트로 분리하기 위한 키 정의입니다.
 * 각 문자열은 해당 컴포넌트가 실제로 참조하는 키만 포함합니다.
 */
const contextKeys = (value) => Object.freeze(value.split(' '));

export const APP_CONTEXT_GROUP_KEYS = Object.freeze({
  user: Object.freeze({
    shell: contextKeys('Button currentAuthRoleReady firebaseAuthReady firebaseAuthUser hasFirebaseAuthSession isUserDirectoryAccessRestricted triggerToast userProfile userProfileReady userTab'),
    home: contextKeys('formatFirestoreDate goToProtectedUserTab goToUserFaq goToUserHome goToUserLogin goToUserMypage goToUserNotice goToUserSignup hasFirebaseAuthSession noticePosts noticePostsLoadErrorMessage noticePostsReady openNoticePost siteSettings stats'),
    rental: contextKeys('Badge Button Card CardContent Info LockIcon STATUS Search availabilityFilter availableFilterLabel currentAuthRoleErrorMessage currentAuthRoleReady currentUserRentalRestrictionStatus currentUserRestrictionReady data filteredLaptops firebaseAuthReady firebaseAuthUser form formatDateWithKoreanWeekday getLaptopRentalAvailability getSafeMaxRentalDays getUserLaptopStatusLabel goToUserLogin goToUserMypage isCurrentFirebaseAuthGeneralUser isPeriodBasedRentalMode motion query rentalDeviceSectionDescription rentalDeviceSectionTitle rentalStartAdjustmentInfo requestSubmitLoading selectedAssetCategory selectedLaptop selectedLaptopAvailability selectedLaptopId setAvailabilityFilter setForm setQuery setSelectedAssetCategory setSelectedLaptopId submitRequest triggerToast unavailableFilterLabel userProfile userProfileReady'),
    myPage: contextKeys('Button Card CardContent Input Users adminMyProfileForm adminMyProfileSaving cancelWithdrawal currentAuthAdminAccount currentAuthRoleReady data firebaseAuthUser goToUserHome goToUserLogin goToUserSignup isAdminAuthenticated isCurrentFirebaseAuthGeneralUser logoutAdmin openWithdrawalDialog pushAppPath saveMyAdminProfile saveMyUserProfile setAdminMyProfileForm setUserProfileForm setView setWithdrawalPassword submitMembershipWithdrawal userDirectoryVerificationLoading userProfile userProfileForm userProfileReady userProfileSaving withdrawalBlockMessage withdrawalDialogOpen withdrawalLoading withdrawalPassword triggerToast'),
    auth: contextKeys('Button Card CardContent Input Users accountRecoveryForm accountRecoveryLoading accountRecoveryResult cancelUserSignup data firebaseAuthReady firebaseAuthUser hasEstablishedUserSession goToProtectedUserTab goToUserEmailRecovery goToUserLogin goToUserPasswordReset goToUserSignup logoutUser passwordResetForm passwordResetLoading passwordResetStage passwordResetVerificationResult resetAccountRecoverySearch setAccountRecoveryForm siteSettings submitAccountRecovery submitPasswordReset submitUserAuthForm triggerToast updatePasswordResetForm setUserAuthForm userAuthForm userAuthLoading userTab'),
    accountStatus: contextKeys('AlertCircle Button Card CardContent CheckCircle2 Clock UserCircle goToProtectedUserTab goToUserHome goToUserLogin siteSettings userAccountStatusView'),
    history: contextKeys('ADMIN_REQUEST_PAGE_SIZE_OPTIONS ADMIN_REQUEST_TAB Badge Button Card CardContent ClipboardList RENTAL_EXTENSION_APPROVAL_MODE STATUS Search USER_REQUEST_ACTION USER_REQUEST_REVIEW_STATUS currentAuthAdminAccount currentAuthRoleReady currentUserRentalRestrictionStatus currentUserRequests data firebaseAuthReady firebaseAuthUser formatDateWithKoreanWeekday formatFirestoreTimestamp getExtensionRequestAvailableDate getRentalExtensionPeriod getRequestDisplayStatus getRequestExtensionCount getSafeRentalExtensionDays getSafeRentalExtensionMaxCount getUserRequestActionLabel getUserRequestReviewStatusLabel goToProtectedUserTab isAdminAuthenticated openUserActionDialog rentalRequestsLoadErrorMessage rentalRequestsReady userActionSaving userProfile'),
    footerPage: contextKeys('AlertCircle Button Card CardContent footerPagesLoadErrorMessage footerPagesReady goToUserHome selectedFooterPage'),
    board: contextKeys('AnimatePresence Button Card CardContent Clock Pin Search activeFaqCategoryId activeFaqCategoryName categoryFilteredFaqPosts closeNoticePost displayedFaqPosts expandedFaqPostId faqCategories faqCategoriesLoadErrorMessage faqCategoriesReady faqCategoryNameById faqPostsLoadErrorMessage faqPostsReady faqQuery faqSearchWithinCategory faqTotalPages formatFirestoreDate goToUserHome motion noticePosts noticePostsLoadErrorMessage noticePostsReady noticeRegularPostNumberById noticeTotalPages openNoticePost paginatedNoticePosts pinnedNoticePosts regularFaqPosts regularNoticePosts safeFaqPage safeNoticePage selectedNoticePost setActiveFaqCategoryId setExpandedFaqPostId setFaqPage setFaqQuery setFaqSearchWithinCategory setNoticePage setUserNoticeQuery toggleFaqPost userNoticeQuery userTab'),
  }),
  admin: Object.freeze({
    shell: contextKeys('AlertCircle Button Card CardContent ClipboardList Clock Input Laptop LayoutDashboard LockIcon React Settings ShieldCheck UserCircle Users adminAccountsLoadErrorMessage adminAuthForm adminAuthLoading adminTab authenticateAdmin currentAuthRoleErrorMessage goToUserHome handleAdminTabChange setAdminAuthForm setAdminTab shouldShowAdminAccountsErrorPage shouldShowAdminLoadingPage shouldShowAdminLoginPage'),
    dashboard: contextKeys('ADMIN_REQUEST_QUICK_FILTER ADMIN_REQUEST_TAB AdminPageHeader STATUS USER_PROFILE_STATUS USER_REQUEST_ACTION USER_REQUEST_REVIEW_STATUS dashboardSummary dashboardSummaryLoadErrorMessage dashboardSummaryReady dashboardSummaryRefreshing data defaultRentalStartDate formatDateWithKoreanWeekday getMaxRentalDueDate getSafeMaxRentalDays openAdminMemberAccounts openAdminRequests orphanedRentalAvailabilityRequests refreshDashboardSummary rentalStartAdjustmentInfo today'),
    requests: contextKeys('ADMIN_REQUEST_PAGE_SIZE_OPTIONS ADMIN_REQUEST_QUICK_FILTER ADMIN_REQUEST_TAB AdminPageHeader Badge Button Edit3 RENTAL_EXTENSION_APPROVAL_MODE RENTAL_REQUEST_AUDIT_ACTION STATUS Search USER_REQUEST_ACTION USER_REQUEST_REVIEW_STATUS dashboardSummary adminRequestsMutationVersion adminRequestsNavigationRequest adminRequestsPrerequisitesReady adminUserActionSavingRequestId data formatFirestoreTimestamp getExtensionRequestAvailableDate getRentalExtensionPeriod getRequestDisplayStatus getRequestExtensionCount getSafeRentalExtensionMaxCount getUserRequestActionLabel getUserRequestReviewStatusLabel isAdminAuthenticated onAdminRequestsControllerStateChange orphanedRentalAvailabilityRequests renderRequestActionButtons reviewUserActionRequest saveRequestMemo today triggerToast updateRequestMemo commitAdminRequestEdit commitAdminRequestStatusRestore'),
    laptops: contextKeys('AdminPageHeader Badge Button ClipboardList Edit3 Input Plus React STATUS Save Search Select Trash2 adminAvailabilityFilter adminFilteredLaptops adminLaptopQuery adminSelectedAssetCategory authenticatedAdminId createLaptop currentAuthAdminAccount data deleteLaptop editLaptop editLaptopInsertIndex getLaptopAdminDisplayStatus handleAddLaptopClick newLaptop saveLaptop setAdminAvailabilityFilter setAdminLaptopQuery setAdminSelectedAssetCategory setData setEditLaptop setNewLaptop setShowUploadPanel showUploadPanel splitRentalAssets triggerToast'),
    holidaySettings: contextKeys('AdminPageHeader Button ClipboardList DEFAULT_HOLIDAY_TYPE HOLIDAY_TYPE_LABEL Plus Save Trash2 addTempHoliday applyHolidayImportConflictChoice deleteTempHoliday discardHolidayChanges formatDateWithKoreanWeekday getKoreaNow holidayImportConflictModal holidayImportLoading holidayImportYear holidayManagementMonth holidayManagementView holidayManagementYear holidaySettingsDirty importKoreanPublicHolidaysFromJson newHolidayDate newHolidayName newHolidayType saveHolidaySettings setHolidayImportConflictModal setHolidayImportYear setHolidayManagementMonth setHolidayManagementView setHolidayManagementYear setNewHolidayDate setNewHolidayName setNewHolidayType tempHolidayList today updateTempHolidayReason'),
    categories: contextKeys('AdminPageHeader Button Edit3 Plus Save Trash2 X addTempAssetCategory assetCategoryCatalogReady applyEditTempAssetCategory cancelTempAssetCategoryChanges deleteTempAssetCategory draggingAssetCategoryIndex editingAssetCategoryIndex editingAssetCategoryName moveTempAssetCategory newAssetCategory saveTempAssetCategoryChanges setDraggingAssetCategoryIndex setEditingAssetCategoryIndex setEditingAssetCategoryName setNewAssetCategory startEditTempAssetCategory tempAssetCategories'),
    people: contextKeys('AdminPageHeader Button Edit3 Plus Save Trash2 X isSplitStorageReady memberDirectoryBorrowers memberDirectorySettings memberDirectoryTeams onMemberDirectoryDeferredStateChange setData triggerToast'),
    signupPolicy: contextKeys('AdminPageHeader Button authenticatedAdminAccount authenticatedAdminId isAdminAuthenticated isSplitStorageReady memberDirectoryAudit memberDirectoryBorrowers memberDirectoryPolicyEnabled memberIdentityClaimsReady onSignupPolicyDeferredStateChange openAdminMemberAccounts setData signupPolicySettings triggerConfirm triggerToast'),
    noticePosts: contextKeys('AdminPageHeader Button Edit3 NOTICE_POSTS_PER_PAGE_OPTIONS Pin Search Trash2 adminNoticeQuery adminNoticeTotalPages adminPinnedNoticePosts adminRegularNoticePosts confirmDeleteNoticePost discardNoticeBoardConfigChanges formatFirestoreDate noticeBoardConfigLoadErrorMessage noticeBoardConfigReady noticeBoardConfigSaving noticePostDeletingId noticePosts noticePostsLoadErrorMessage noticePostsPerPageInput noticePostsReady noticeRegularPostNumberById noticeRegularTotalCount openNoticePostDialog paginatedAdminNoticePosts safeAdminNoticePage saveNoticeBoardConfig setAdminNoticePage setAdminNoticeQuery setNoticePostsPerPageInput'),
    siteSettings: contextKeys('AdminPageHeader Button Input Select authenticatedAdminAccount finalizeSplitStorageMigration isSplitStorageReady siteSettings siteSettingsLoadErrorMessage siteSettingsReady splitStorageFinalizeLoading systemAdminSettings systemAdminSettingsLoadErrorMessage systemAdminSettingsReady triggerConfirm triggerToast'),
    homeManagement: contextKeys('AdminPageHeader Button Input Select authenticatedAdminAccount authenticatedAdminId finalizeSplitStorageMigration isAdminAuthenticated isSplitStorageReady siteSettings siteSettingsLoadErrorMessage siteSettingsReady splitStorageFinalizeLoading systemAdminSettings systemAdminSettingsLoadErrorMessage systemAdminSettingsReady triggerConfirm triggerToast'),
    popupPosts: contextKeys('AdminPageHeader Button confirmDeletePopupPost formatPopupDateTime getPopupDisplayStatus movePopupPost openPopupPostDialog popupPostDeletingId popupPostToggleSavingId popupPosts popupPostsLoadErrorMessage popupPostsReady togglePopupPostEnabled'),
    faqPosts: contextKeys('AdminPageHeader AnimatePresence Button Edit3 FAQ_POSTS_PER_PAGE_OPTIONS Search activeFaqCategoryId activeFaqCategoryName addFaqCategory adminExpandedFaqPostId adminFaqTotalPages adminPinnedFaqPosts adminRegularFaqPosts confirmDeleteFaqCategory confirmDeleteFaqPost discardFaqBoardConfigChanges editingFaqCategoryId editingFaqCategoryName faqBoardConfigLoadErrorMessage faqBoardConfigReady faqBoardConfigSaving faqCategories faqCategoriesLoadErrorMessage faqCategoriesReady faqCategoryDeletingId faqCategoryNameById faqCategorySavingId faqPostDeletingId faqPosts faqPostsLoadErrorMessage faqPostsPerPageInput faqPostsReady faqQuery faqRegularTotalCount faqSearchWithinCategory motion newFaqCategoryName openFaqPostDialog paginatedAdminFaqPosts safeAdminFaqPage saveFaqBoardConfig saveFaqCategoryName setActiveFaqCategoryId setAdminExpandedFaqPostId setAdminFaqPage setEditingFaqCategoryId setEditingFaqCategoryName setFaqPostsPerPageInput setFaqQuery setFaqSearchWithinCategory setNewFaqCategoryName startEditFaqCategory toggleAdminFaqPost'),
    footerManagement: contextKeys('AdminPageHeader Button closeFooterPageDialog confirmDeleteFooterPage footerConfigDraft footerConfigLoadErrorMessage footerConfigReady footerConfigSaving footerPageDeletingId footerPageDialog footerPageForm footerPageSaving footerPageToggleSavingId footerPages footerPagesLoadErrorMessage footerPagesReady formatFirestoreDate moveFooterPage openFooterPageDialog saveFooterConfig saveFooterPage setFooterConfigDraft setFooterPageForm toggleFooterPageEnabled triggerConfirm'),
    memberAccounts: contextKeys('AdminPageHeader Button CheckCircle2 LogOut Search USER_PROFILE_STATUS XCircle adminMemberAccountsNavigationRequest isAdminAuthenticated memberAccountsPrerequisitesReady memberDirectoryBorrowers memberDirectoryPolicyEnabled memberDirectoryTeams registeredAdminAccounts triggerConfirm triggerToast'),
    adminAccounts: contextKeys('ADMIN_ACCOUNT_PAGE_SIZE ADMIN_CUSTOM_OPTION_VALUE AdminPageHeader Button Input Search Select adminAccountEditForm adminAccountForm adminAccountTotalPages adminAccountUserOptions authenticatedAdminAccount authenticatedAdminId cancelEditAdminAccount changeAdminAccountPassword createDefaultAdminAccountForm data deleteAdminAccount editingAdminAccountId paginatedAdminAccounts registerAdminAccount registeredAdminAccounts safeAdminAccountPage saveAdminAccountEdit setAdminAccountEditForm setAdminAccountForm setAdminAccountPage startEditAdminAccount toggleAdminAccountLock'),
    serviceOperations: contextKeys('AdminPageHeader Button Input Select authenticatedAdminAccount finalizeSplitStorageMigration isSplitStorageReady siteSettings siteSettingsLoadErrorMessage siteSettingsReady splitStorageFinalizeLoading systemAdminSettings systemAdminSettingsLoadErrorMessage systemAdminSettingsReady triggerConfirm triggerToast'),
    accountSecurity: contextKeys('AdminPageHeader Button authenticatedAdminAccount rebaseAdminAuthenticatedSession setSystemAdminSettings setUserSessionPolicy systemAdminSettings systemAdminSettingsLoadErrorMessage systemAdminSettingsReady triggerToast userSessionPolicy userSessionPolicyLoadErrorMessage userSessionPolicyReady'),
    dataManagement: contextKeys('AdminPageHeader Button Input Select authenticatedAdminAccount finalizeSplitStorageMigration handleAdminTabChange openAdminRequests isSplitStorageReady siteSettings siteSettingsLoadErrorMessage siteSettingsReady splitStorageFinalizeLoading systemAdminSettings systemAdminSettingsLoadErrorMessage systemAdminSettingsReady triggerConfirm triggerToast'),
    systemInfo: contextKeys('AdminPageHeader Button Input Select authenticatedAdminAccount finalizeSplitStorageMigration isSplitStorageReady siteSettings siteSettingsLoadErrorMessage siteSettingsReady splitStorageFinalizeLoading systemAdminSettings systemAdminSettingsLoadErrorMessage systemAdminSettingsReady triggerConfirm triggerToast'),
    extensionSettings: contextKeys('AdminPageHeader Button DEFAULT_EXCLUDE_HOLIDAYS_FOR_START_DATE DEFAULT_EXCLUDE_SATURDAYS DEFAULT_EXCLUDE_SUNDAYS DEFAULT_WORK_END_TIME OVERDUE_PENALTY_MODE RENTAL_EXTENSION_APPROVAL_MODE Save data getKoreaNow handleAdminTabChange saveSystemSettings setTempSettings tempAllowNonOverlappingSameAssetRequests tempBusinessDayAdjustmentEnabled tempSettings triggerToast'),
  }),
  app: Object.freeze({
    footer: contextKeys('footerConfig footerPages openFooterPage selectedFooterPageId userTab'),
    dialogs: contextKeys('AlertCircle AnimatePresence Button CheckCircle2 DateInputWithWeekday Input Select USER_REQUEST_ACTION X activeUserActionRentalRequest closeFaqPostDialog closeNoticePostDialog closePopupPostDialog closeUserActionDialog confirmModal data faqCategories faqPostDialog faqPostForm faqPostSaving formatDateWithKoreanWeekday getAdjustedRentalDueDate getMaxRentalDueDate getRentalDueDateAdjustmentReason getRentalExtensionApprovalMode getRentalExtensionPeriod getUserRequestActionLabel motion noticePostDialog noticePostForm noticePostSaving popupPostDialog popupPostForm popupPostSaving saveFaqPost saveNoticePost savePopupPost setConfirmModal setFaqPostForm setNoticePostForm setPopupPostForm setToast setUserActionForm submitUserActionRequest toast today triggerToast userActionDialog userActionForm userActionSaving'),
    popup: contextKeys('dismissAllUserPopups dismissUserPopup dismissedPopupLocalVersions dismissedPopupSessionVersions firebaseAuthUser popupPosts temporarilyDismissedPopupVersions userTab'),
  }),
});

const USER_TAB_CONTEXT_KEY = Object.freeze({
  home: 'home',
  rental: 'rental',
  mypage: 'myPage',
  login: 'auth',
  signup: 'auth',
  findEmail: 'auth',
  resetPassword: 'auth',
  accountStatus: 'accountStatus',
  history: 'history',
  footerPage: 'footerPage',
  notice: 'board',
  faq: 'board',
});

export const getUserPanelContextKey = ({
  userTab,
  hasFirebaseAuthSession,
  isUserDirectoryAccessRestricted,
}) => {
  const isProtectedTab = PROTECTED_USER_TABS.has(userTab);

  if (isProtectedTab && !hasFirebaseAuthSession) return 'auth';
  if (isProtectedTab && isUserDirectoryAccessRestricted) return 'myPage';

  return USER_TAB_CONTEXT_KEY[userTab] || 'board';
};

const ADMIN_TAB_CONTEXT_KEY = Object.freeze({
  dashboard: 'dashboard',
  requests: 'requests',
  laptops: 'laptops',
  holidaySettings: 'holidaySettings',
  categories: 'categories',
  people: 'people',
  signupPolicy: 'signupPolicy',
  noticePosts: 'noticePosts',
  siteSettings: 'siteSettings',
  homeManagement: 'homeManagement',
  popupPosts: 'popupPosts',
  faqPosts: 'faqPosts',
  footerManagement: 'footerManagement',
  memberAccounts: 'memberAccounts',
  adminAccounts: 'adminAccounts',
  serviceOperations: 'serviceOperations',
  accountSecurity: 'accountSecurity',
  dataManagement: 'dataManagement',
  systemInfo: 'systemInfo',
  extensionSettings: 'extensionSettings',
  settings: 'serviceOperations',
  homeContent: 'homeManagement',
  heroBanners: 'homeManagement',
  promotionBanners: 'homeManagement',
  quickLinkBanners: 'homeManagement',
});

export const getAdminPanelContextKey = (adminTab) =>
  ADMIN_TAB_CONTEXT_KEY[adminTab] || 'dashboard';
